### ISSUE TITLE
Mobile: Header takes up full screen, not obvious screen has changed

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#21]
With the header links taking up the whole screen, clicking any of the links except "Coummunity" and there are no visible changes to the page even though the page has changed.

The problem clearly stated is there is no feedback to notify the user the page has actually changed. 

For me the header links are displayed in a single vertical column with plenty of white space padding. If instead they were horizontal in two rows perhaps, then you could actually see the whole page and would not have  to scroll down to see the content.

**Comment by williamdekryger** [comment]
Right. Mobile is still languishing on my ever-mounting list of tasks. If you have time, find as many websites with good looking menus as you can find, and send them to me for inspiration :grinning:

**Comment by williamdekryger** [comment]
@DanVanAtta I addressed a few of the other mobile tasks in #34. Is this still an issue, and if so, how do you propose fixing it?

**Comment by ZjelcoP** [comment]
My thoughts when going through the headers:
1: I really prefer them as buttons or blocks instead of just the words. It makes them much more obvious as interactive links and more inviting to actually click on it. Now at first all headers together look like one long sentence.
2: Rearranging: Think the download button can go as you have a big one prominently for that.
Rest: my choice of order would be:
-Community (Could do with blocks just like the contribute page for better overview)
-Maps 
-Help and documentation
-Contribute (could do with a short explanation why we need people to contribute. Many people have no clue what "open source" means. My explaining words for the Facebook-page: "It's free, non-commercial and built entirely by enthousiasts for the glory of TripleA!")

**Comment by DanVanAtta** [comment]
- we need to determine if this is still a problem, probably is. In which case we are simply tracking it it here until someone volunteers a fix.

**Comment by DanVanAtta** [comment]
I think this issue can be re-summarized as this:
- the header is not very mobile friendly, it takes up the entire page on mobile, and when clicking links, there is no way to tell which page you are on without scrolling (IE: missing feedback that the correct page transition has occurred)

**Comment by williamdekryger** [comment]
I may be able to provide a fix, though I'm not sure what beyond condensing the menu into one link, and using Javascript to open it up, though I don't know if that is what we need...

**Comment by DanVanAtta** [comment]
Closing for now. A QA pass on mobile would be a good idea.
