### ISSUE TITLE
What should we do with broken links?

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea-game.github.io#213]
After 2 day of trial and error, I finally got a new travis script for this website working!
(We might need some html validation of the triplea_maps.yaml file, but this is off-topic).
In [this travis log](https://travis-ci.org/RoiEXLab/triplea-game.github.io/builds/239376575) you can see, that only 1 Test is failing.
I wrote [a tool](https://github.com/RoiEXLab/link-checker) today which parses every html file recursively in a directory, and extracts every link (except for the ones in js code) and checks the existance on a specified "local" server.
There are actually quite a lot 404 errors, and a single 503, mostly in legacy documents.
What should we do with those "broken links"?
Delete them? Replace them? Mark them as "broken"?
This is the last issue to adress before I can create a clean PR. (My test branches are currently cluttered with 30+/50+ commits with just 2 files changed)

**Comment by ron-murhammer** [comment]
@RoiEXLab Can you post a list of the broken links? I would say let's do a quick review of them.

**Comment by RoiEXLab** [comment]
Ah, it seems I wasn't clear enough... 
Just watch the logfile from travis I linked...

**Comment by ron-murhammer** [comment]
Oh I see, didn't realize that.

So a good chunk of them are from the "news" page which I'm not sure how to even navigate to. They are trying to refer to old release notes in SourceForge. It would seem that whole page should just be removed in favor of http://www.triplea-game.org/release_notes/

**Comment by ssoloff** [comment]
```
Link 'http://localhost:4000/playing_the_game_engine_readme/./doc/game_playing_guide.html#sec_8' returned code 404
	Affected Files:
		/home/travis/build/RoiEXLab/triplea-game.github.io/_site/playing_the_game_engine_readme/index.html
```

I think the problem is simply out-dated links in the HTML.  Those links should probably be using the Jekyll permalink for `game_playing_guide.html`.  If I try to hit `http://localhost:4000/game_playing_guide/index.html#sec_8`, I get the expected content.  If I change the corresponding link in `dev_docs/older/readme.html` to `/game_playing_guide/#sec_8`, it works correctly.

(This comment applies to all missing links to `game_playing_guide.html`.  But it probably also applies to all similar intra-site link errors.)

<hr>

```
Link 'https://cloud.githubusercontent.com/assets/12397753/21297739/fdc589ee-c539-11e6-9209-ba75b7707700..png' returned code 403
	Affected Files:
		/home/travis/build/RoiEXLab/triplea-game.github.io/_site/game_playing_guide/index.html
```

This just looks like a fat finger with the two dots between the file name and extension.  When I remove one of the dots, the URL resolves to an image.
