### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea-game.github.io#24]
My first post on github =)

Regarding the website:
Why is there no favicon.ico? (The little icons used by the browsers) When I save the website link in my browser there is just a generic Internet Explorer icon. I think the favicon should just be placed at the website root where the index.html is.

One can make a favicon easily. Here a TripleA one that I made:
https://dl.dropboxusercontent.com/u/91867373/FaviconOnly.zip
Normally the icon would be used if one included the following code in the head of the HTML document:
https://dl.dropboxusercontent.com/u/91867373/FaviconOnlyTXT.zip (Cant post the code here for some reason)

I think the following is to be used if the icon should be supported by Android, Microsoft, and iOS (iPhone and iPad) Apps:
https://dl.dropboxusercontent.com/u/91867373/AllOSFavicon.zip
The instruction is: “After generating a favicon with this tool download and save to the root directory of your site. Then include the following code in the head of your HTML document.”:
https://dl.dropboxusercontent.com/u/91867373/AllOSFaviconTXT.zip

**Comment by DanVanAtta** [comment]
The updates can be made. It seems odd the favicon is in a zip. Looks like a bit more research on exactly how to do it will be needed. Also seems like having the favicon ready will make it a quick task too - thanks : )

**Comment by DanVanAtta** [comment]
Congrats @FrostionAAA 

You'll be able to use the same login for the maps chat: https://gitter.im/triplea-maps/Project

The website chat room on gitter is currently locked to admins, I've asked @ron-murhammer if he can find a way to update that.

**Comment by FrostionAAA** [comment]
I placed the files in zip. I could not post them any other way. They must not be in zip in when/if they are used on in the website dir.

**Comment by DanVanAtta** [comment]
I think i'll have a chance later tonight to add the files, otherwise will be Monday if @williamdekryger  does not get to it faster.

FYI @FrostionAAA , if it interests you can create a fork which would allow you to directly suggest adding files. Once you've got a fork, follow these steps to get set up locally: https://github.com/triplea-maps/Project/wiki/Map-Makers:-Setup-Instructions, you'll be cloning your fork, adding the files, commiting, then pushing them to your fork. Then the next time you visit your github fork's home page, there is will be a link where you can submit a "pull request".

**Comment by williamdekryger** [comment]
That is good. I had not thought about that yet, but another good find by @FrostionAAA
