### ISSUE TITLE
Add the lobby rules to website

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea-game.github.io#77]
Lobby rules are here: http://www.tripleawarclub.org/modules/newbb/viewtopic.php?topic_id=100&forum=1

**Comment by prastle** [comment]
Ok yes they are there and in help tab of game problem is?

**Comment by prastle** [comment]
Also on git hub page as I recall but let me check ah you have to dig so add a link and while on subject why veq still a donation link ? ;)  It should be money towards our site as a private con we had oncel  Just my thoughts

Pras

**Comment by DanVanAtta** [comment]
Could you clarify  @prastle ? 
Task here is to host the game rules on a static page. Easier to manage there. We likely have the same rules somewhere on the dev forum.

**Comment by prastle** [comment]
no task here was to write player rules
 and mod rules
which are both the same

game rules we have elsewhere

**Comment by prastle** [comment]
above post link covers them thus why we here?

**Comment by DanVanAtta** [comment]
A forum post is a poor choice for rules location.  Example, there is a 'no-politics' rule that is not listed.

It is static content, there is no need to store that on warclub. Migrated we have an opportunity to discuss changes to evolve the rules more easily, rather than locking a thread.

**Comment by ZjelcoP** [comment]
I offered to help on organizing documentation and info. At the moment looking for info you'll be taken over several websites and fora, sometimes having to go through a whole thread hopefully finding what is the current position on any point.

My aim would be to organize all that including lobby rules as static content easily accessible through tabs in website. Related forum threads can serve merely to discuss contents or changes to static info and ask questions.

Where to store this content? Eventually I'd like to see it in one place with everything else but i believe that is a different discussion somewhere else. As long as the user doesn't get the feeling of being sent all over the web. If he actually is but doesn't notice it, fine.

**Comment by prastle** [comment]
It states when you enter lobby  "No Politics".  I am certain we could add a line to the rules saying no political discussions will be appreciated or something like that since it already says 

3) Names with a political or religious or ideological agenda

  I am quite certain if people are PBEM or PBF they are not talking politics.  But if they are in their own private games who cares.  This rule evolved from the many arguments live that occurred in lobby.  I am fairly certain everyone realizes this.  It was locked after many long days of discussion by many mods.  None of those are involved here in this conversation I might add  ;)

**Comment by DanVanAtta** [comment]
The goal is to have static content, like a rules posting, not be a forum post. Task is to add a copy of the forum post to either the github IO website, or the warclub website (or a new future tech stack version of warclub)

**Comment by Cernelius** [comment]
I believe the no talking politics rule apply to lobby only, not to forum, and I think the developer forum is ruleless (not sure).

If you want to extend the no talking politics rule to forum too, I think you should inform the mods.

**Comment by prastle** [comment]
Yes Cernel u are correct and well put.  It concerns the lobby and live only no one wants to read the argument.

**Comment by williamdekryger** [comment]
Alright everyone, I don't believe this is the appropriate place to be debating forum/lobby rules, but features related to the website. What is the verdict? To add, or not to add?

@ZjelcoP I've also been looking at TripleA's scattered documentation, and I'd be willing to work together on it. I envision a grand documentation section on the website at some point. Let's talk more about this at some point.

**Comment by prastle** [comment]
Ty William we are agreed on something here. :)

in my ho if they cared about the rules they would read them.

static or a link

jmho

more rules means nothing

jmho

**Comment by prastle** [comment]
@ZjelcoP   I hear ya on the gathered documentation.  The sad truth is that live players pretend they have never seen it.  With multiple nick names and etc this is hard to prove. so truth be told
1 login
1 name 
1 email
etc is only solution
u guys are the tech guys
what ever version u come up with if user friendly it will pass
JMHO
Pras

**Comment by Cernelius** [comment]
Having the rules hosted in two different places is a bad idea. I can see them being modified in one and not the other, so we end up with different rules.

Rules should be hosted in 1 place only (and possibly linked to in multi); so either the WarClub or the GitHub WebSite or something.

If not in WarClub, then the WarClub must have a link to them in the main page.

Of course, lobby/forum rules are not definitive, and the appropriate place to debate them is currently the WarClub Bunker. Probably the Username rules should be moved up, since as it is it is not clear they are general rules, applying both to Forum and Lobby. Also, one might argue that it is strange in Forum you can't have political agenda names, yet you can talk politics.

These rules have never meant to be relevant for the Developer forum, nor any forums beside the WarClub only.

If the matter would be removing the rules from WarClub, a Topic in Bunker would be in order.

**Comment by Cernelius** [comment]
Yes and no on Users and Moderators having the same rules.

For example, since rules do not apply to private hosts, a normal User can go in all private hosts and insult everyone or whatever as much as he wishes. But we probably don't want a moderator to do that. Plus moderators have additional Bunker info about the rules (example: Bot rules), tho they are meant to apply to normal users and moderators all the same.

**Comment by DanVanAtta** [comment]
It's a subjective choice we are making when choosing to host content as a forum post, or a webpage. It is a question of location and presentation here, not content.

Does anyone know if it was discussed why rules would be posted on a forum thread, and not be posted on a webpage? I would suggest that an all-of-the-above approach was taken to documentation without concerted effort to ensure a consistent presentation. For example, rule book is a PDF hosted on source forge, map making instructions is an unlinked Readme.html file that is installed with the game, lobby rules are in a warclub forum post, help instructions for hosting, map downloads and other tasks are on a sourceforge forum post.

The "http://www.triplea-game.org/docs/" page right now is intended to be a centralized spot for all of this, if not links, then hosting the content itself. (the page kinda sucks right now, not much work has been put into it. Presumably when we get our docs well organized, we'll have put some work in so the presentation is a bit better - for now the content of the page is not well defined)


Referencing some previous discussion: https://github.com/triplea-game/triplea/issues/1070, there was consensus that static, informational content should be a webpage, not a forum post. Are there good reasons why we would want to keep the lobby rules as a warclub forum post, and would not want it migrated to a webpage?

**Comment by prastle** [comment]
It was originally put in warclub because at that time most user's were visiting warclub a lot I would assume.

**Comment by DanVanAtta** [comment]
Then why were the how to host and download instructions put in source forge forums? Does it still make sense to have the respective rules be posted in those locations? The various rules, docs, are not even consolidated to a centralized index. It would seem to me that the first step would be to at least have links to it all in one spot. Thinking ahead, the forum posts do not have consistent presentation, and cannot easily be improved further. It makes sense to cut out the links in cases where the content is better hosted as a webpage.

**Comment by prastle** [comment]
They were placed in source forge because ones interested in development download and hosting were more tech involved.  To refresh tho all in one spot fine.  I'm sure that makes little difference only a certain few will read sadly.

**Comment by prastle** [comment]
thus more traffic 1 site the best idea.  

Jmho

Pras

**Comment by DanVanAtta** [comment]
Hmm, in both cases the audience of the rules/information were players, not necessarily just map makers etc. One is the tips on host a game in the lobby, and another are rules for lobby conduct, both are directed towards players.

I think the point is made, the documentation is scattered and got that way out of a matter of convenience. Which then gets us to this task, migrate such content to a centralized location, host it in a more conventional format, and failing the above, add links to it all.

**Comment by prastle** [comment]
Just copy paste

**Comment by prastle** [comment]
To bring the rules thing back up again sorry.  It doesn't really matter where we put them. If they pretend they never read.  Best is still one login and read rules and sign off. Then they get download etc.  Meanwhile if they can log in under multiple knicks it makes no difference.  Just my thoughts

**Comment by DanVanAtta** [comment]
closing, we have conslidated docs on the website, a link to the rules is there. We would do well to import the forum text to a source controlled markdown file, but for now at least it can easily be found along with the rest of documentation.

To make users actually read the lobby rules is out of scope for this issue, please create a new one (it is an involved discussion). I'll note though that we do display the link to the lobby rules in the welcome message.
